### ISSUE TITLE
Is there any method to use dotmask with D435i?

### ISSUE THREAD

**Issue by frankSARU** [introlab/dotmask#2]
I am trying to use dotmask but I only have D435i to use

**Comment by j20100** [comment]
I don't have a D435i at hand, but if it publish an RGB image and a depth image it should work. Do you have issues running Dotmask with the D435i?

**Comment by frankSARU** [comment]
I used the rs_rgbd launch file that comes with the realsense package to start my camera and then posted a series of topics, but there seems to be some required topics missing for dotmask, and nothing is shown accordingly in the rviz interface.
Here's my published topics:
`/camera/align_to_color/parameter_descriptions
/camera/align_to_color/parameter_updates
/camera/aligned_depth_to_color/camera_info
/camera/aligned_depth_to_color/image_raw
/camera/aligned_depth_to_color/image_raw/compressed
/camera/aligned_depth_to_color/image_raw/compressed/parameter_descriptions
/camera/aligned_depth_to_color/image_raw/compressed/parameter_updates
/camera/aligned_depth_to_color/image_raw/compressedDepth
/camera/aligned_depth_to_color/image_raw/compressedDepth/parameter_descriptions
/camera/aligned_depth_to_color/image_raw/compressedDepth/parameter_updates
/camera/aligned_depth_to_color/image_raw/theora
/camera/aligned_depth_to_color/image_raw/theora/parameter_descriptions
/camera/aligned_depth_to_color/image_raw/theora/parameter_updates
/camera/color/camera_info
/camera/color/image_raw
/camera/color/image_raw/compressed
/camera/color/image_raw/compressed/parameter_descriptions
/camera/color/image_raw/compressed/parameter_updates
/camera/color/image_raw/compressedDepth
/camera/color/image_raw/compressedDepth/parameter_descriptions
/camera/color/image_raw/compressedDepth/parameter_updates
/camera/color/image_raw/theora
/camera/color/image_raw/theora/parameter_descriptions
/camera/color/image_raw/theora/parameter_updates
/camera/color/image_rect_color
/camera/color/image_rect_color/compressed
/camera/color/image_rect_color/compressed/parameter_descriptions
/camera/color/image_rect_color/compressed/parameter_updates
/camera/color/image_rect_color/compressedDepth
/camera/color/image_rect_color/compressedDepth/parameter_descriptions
/camera/color/image_rect_color/compressedDepth/parameter_updates
/camera/color/image_rect_color/theora
/camera/color/image_rect_color/theora/parameter_descriptions
/camera/color/image_rect_color/theora/parameter_updates
/camera/color_rectify_color/parameter_descriptions
/camera/color_rectify_color/parameter_updates
/camera/depth/camera_info
/camera/depth/image_rect_raw
/camera/depth/image_rect_raw/compressed
/camera/depth/image_rect_raw/compressed/parameter_descriptions
/camera/depth/image_rect_raw/compressed/parameter_updates
/camera/depth/image_rect_raw/compressedDepth
/camera/depth/image_rect_raw/compressedDepth/parameter_descriptions
/camera/depth/image_rect_raw/compressedDepth/parameter_updates
/camera/depth/image_rect_raw/theora
/camera/depth/image_rect_raw/theora/parameter_descriptions
/camera/depth/image_rect_raw/theora/parameter_updates
/camera/depth_registered/dynamic_masked_image_raw
/camera/depth_registered/image_raw
/camera/depth_registered/masked_image_raw
/camera/depth_registered/points
/camera/extrinsics/depth_to_color
/camera/motion_module/parameter_descriptions
/camera/motion_module/parameter_updates
/camera/realsense2_camera_manager/bond
/camera/rgb/image_rect_color
/camera/rgb_camera/auto_exposure_roi/parameter_descriptions
/camera/rgb_camera/auto_exposure_roi/parameter_updates
/camera/rgb_camera/parameter_descriptions
/camera/rgb_camera/parameter_updates
/camera/stereo_module/auto_exposure_roi/parameter_descriptions
/camera/stereo_module/auto_exposure_roi/parameter_updates
/camera/stereo_module/parameter_descriptions
/camera/stereo_module/parameter_updates
/diagnostics
/rosout
/rosout_agg
/tf
/tf_static`

And here's the error warnings and rviz interface.
![2021-06-29 16-44-30 的屏幕截图](https://user-images.githubusercontent.com/24972250/123759782-ce508200-d8f2-11eb-9765-d4b1266f46f0.png)
![2021-06-29 16-45-10 的屏幕截图](https://user-images.githubusercontent.com/24972250/123759804-d3153600-d8f2-11eb-984a-253231cb3c8e.png)

Since the D435i doesn't publish topics like `/camera/rgb/image_raw`, I modified the files in dotmask that refer to this topic and changed them all to the d435i's `/camera/color/image_raw` format

**Comment by j20100** [comment]
It seems that DOTMASK cannot subscribe to _/camera/color/image_rect_color_ and  _/camera/color/camera_info_ . However, the D435i seems to be able to publish those topics (you may need to remap them). Have you tried to run the _rs_rtabmap.launch_ from the realsense-ros package?

**Comment by frankSARU** [comment]
I've tried to use rs_rtabmap.launch and it has other problems. For remap, I have remap all the topic to my topic list like this, the error still exists. By the way, I can use opensource_tracking.launch properly with my d435i.
![2021-07-12 18-02-43 的屏幕截图](https://user-images.githubusercontent.com/24972250/125261021-d8836f00-e33b-11eb-84b9-17d70cb8724c.png)

**Comment by j20100** [comment]
Could you send me a rosbag? It would make it easier to debug.

**Comment by frankSARU** [comment]
> Could you send me a rosbag? It would make it easier to debug.

Thanks for your reply! Because I don't know what are you need so I just run a `rosbag record -a` command to record all.
So the file is a little big, I uploaded it on my google drive.
https://drive.google.com/file/d/1Na3hsVI2o8dzE1rG2uZwyXhpvwPd5Xo0/view?usp=sharing
If you need anything else to debug, or I was doing something wrong, plz let me know.
Thanks!

**Comment by mobiiin** [comment]
Having the same error here. have you managed to sort out the issue? @frankSARU
it seems the /rtabmap/odom doesn't publish any messages. wondering what the problem is?

**Comment by j20100** [comment]
I have added the D435i (both a launch file and in dotmask). I used @frankSARU rosbag so i dont know if it will work with a real camera. Let me know if there is any issues. 

To run the code for the D435i use the following steps: 

1. roslaunch dotmask dotmask-D435i.launch 

2. Start the camera

3. source ~/catkin_ws_py3/devel/setup.bash
    cd ~/catkin_ws_py3/src/dotmask/src
    python3 dotmask_node.py --nn=yolact --input=D435i
