### ISSUE TITLE
is it compatible with ros kinetic?

### ISSUE THREAD

**Issue by mobiiin** [introlab/dotmask#3]
Hi, can I compile and run this framework in ubuntu 16, ros kinetic?

**Comment by j20100** [comment]
I do not have a Ubuntu 16 installation at hand to test but I don't think it should be a problem. Have you had any issues?

**Comment by mobiiin** [comment]
thanks for your response,
yes, I can't get cuda 10.2 to work with Ubuntu 16.04, since it needs NVIDIA 440 to be installed and the latest NVIDIA version released for Ubuntu 16 is 430. consequently, the cuda test doesn't pass

**Comment by j20100** [comment]
I will try to run it on ubuntu 16.04 using cuda 10 to see if there are any issues.
