### ISSUE TITLE
why is there two point clouds?

### ISSUE THREAD

**Issue by mobiiin** [introlab/dotmask#4]
![Screenshot from 2021-08-23 19-07-49](https://user-images.githubusercontent.com/47173997/130466640-85b90e06-6f08-41e7-a4f6-9f3af2289b32.png)

Would it be a good idea to install TensorRT to improve performance?

**Comment by j20100** [comment]
From what I can see, its seems that the odometry had an issue with the TF. Does it shift between the two point clouds? If so, it may be that multiple TF are generated from different publishers. 
TensorRT seems like a good idea! I have not tried to implement it yet.
